### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by brekk** [madlib-lang/madlib-website#39]
Ordering doesn't imply interest / value so much as a means of discussing

- [ ] - 1. Editor affordance - make the editor work closer to something like Codepen / CodeSandbox in terms of a popover runnable pane
- [ ] - 2. Typed Hole - It's a great feature with a not great name 😂 but there's prior art, so that's the name for now
- [ ] - 3. User Mode -> Rather than Dark Mode / you pick your user description
   - JS dev - Differences / Commonalities
   - TS dev - Differences / Commonalities
   - Haskell dev - Same & apply feedback from a Haskell engineer
     + How do I make types? (records, sum types, declarations)
     + How do I pattern match?
   - Engineering Manager
   - None of the above - implies all?
- [ ] - 4. Optimizations / Benchmarkies - We did a bunch recently to make things way faster in some dimensions, that's not well captured on the site
- [ ] - 5. Blog affordance, since we currently work somewhat in the dark
- [ ] - 6. The autodoc stuff we afford in secret
- [ ] - 7. Playbook - blocked (in a satisfying way) until we have the Editor, but started a small example repo to create some non-trivial examples to look at
- [ ] - 8. Tooling out of the box — We have a LSP implementation and a VSCode plugin (and an undocumented vim implementation of the same), we should document that
- [ ] - 9. Bundling / working locally / how our module system works

And I'm sure more!

**Comment by brekk** [comment]
https://github.com/madlib-lang/madlib-website/pull/37 - Editor affordance branch

**Comment by brekk** [comment]
Add a Troubleshooting / Debugging common Madlib errors page
